### ISSUE TITLE
brackets-htmllint has timed out after waiting for 10000 ms	

### ISSUE THREAD

**Issue by TheJuniorAde** [htmllint/brackets-htmllint#1]
after installing the extension, i am experiencing this issue:
`brackets-htmllint has timed out after waiting for 10000 ms`
and my code ends up not being linted
![stuck](https://cloud.githubusercontent.com/assets/4305025/5141309/4173c802-715b-11e4-945f-21baa9e5e06b.png)

**Comment by 1951FDG** [comment]
I believe this issue was fixed in **version 0.1.5** which was released Nov 26, 2014
