### ISSUE TITLE
Upload 0.1.6 version

### ISSUE THREAD

**Issue by ficristo** [htmllint/brackets-htmllint#5]
It seems to me that the latest version isn't uploaded yet to the registry.
It would be nice to have the latest.

**Comment by ficristo** [comment]
@mlochbaum ping?

**Comment by 1951FDG** [comment]
It would be nice to have latest version uploaded to the registry, to avoid having to do it manually!

**Comment by mlochbaum** [comment]
Done!

**Comment by ficristo** [comment]
Thank you!
