### ISSUE TITLE
img-alt-require not working as expected

### ISSUE THREAD

**Issue by 1951FDG** [htmllint/brackets-htmllint#6]
```
<div id="visualization" class="visualization"><img class="ui centered image" src="images/SixtyFourChart.png" height="500" alt=""> </div>
```

The above code produces a warning: attribute values cannot be empty (E006). It shoudn't.

If I remove the class, then no warning is thrown.

```
<div id="visualization" class="visualization"><img src="images/SixtyFourChart.png" height="500" alt=""> </div>
```

**Comment by mlochbaum** [comment]
For future reference, these types of issues with the underlying linter should be posted to the htmllint repository.

I can't reproduce your first error (I don't get the E006 when linting that html). Corrections to img-req-alt are on the way in a few minutes.

**Comment by mlochbaum** [comment]
See https://github.com/htmllint/htmllint/commit/45ddd73fdca621911a9b486066b3c3c8704dfb42.
